/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface Announcements {
  body: string;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  published: Generated<boolean>;
  title: string;
}

export interface AuditionSubmissions {
  age: number | null;
  createdAt: Generated<Timestamp>;
  email: string | null;
  experience: string | null;
  fullName: string;
  id: Generated<Int8>;
  message: string | null;
  phone: string;
}

export interface ContactMessages {
  createdAt: Generated<Timestamp>;
  email: string | null;
  id: Generated<Int8>;
  message: string;
  name: string;
  phone: string | null;
}

export interface Events {
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  eventDate: Timestamp;
  id: Generated<Int8>;
  status: Generated<string>;
  title: string;
  venue: string;
}

export interface GalleryPhotos {
  caption: Generated<string>;
  createdAt: Generated<Timestamp>;
  featured: Generated<boolean>;
  id: Generated<Int8>;
  imageUrl: string;
  storageKey: string;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  announcements: Announcements;
  auditionSubmissions: AuditionSubmissions;
  contactMessages: ContactMessages;
  events: Events;
  galleryPhotos: GalleryPhotos;
  loginAttempts: LoginAttempts;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.