import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { z } from "zod";
import { useAuth } from "../helpers/useAuth";
import { getAdminContent } from "../endpoints/admin/content_GET.schema";
import { postAdminContent } from "../endpoints/admin/content_POST.schema";
import { Form,FormControl,FormItem,FormLabel,FormMessage,useForm } from "../components/Form";
import { Input } from "../components/Input";
import { Textarea } from "../components/Textarea";
import { Button } from "../components/Button";
import { FileDropzone } from "../components/FileDropzone";
import { PageShell } from "../components/PageShell";
import styles from "./admin.module.css";
const eventSchema=z.object({title:z.string().min(2),eventDate:z.string().min(1),venue:z.string().min(2),description:z.string().optional()});
const announcementSchema=z.object({title:z.string().min(2),body:z.string().min(3)});
export default function Admin(){
  const {authState,logout}=useAuth();const qc=useQueryClient();const q=useQuery({queryKey:["admin-content"],queryFn:getAdminContent});
  const [tab,setTab]=useState("overview");const [notice,setNotice]=useState("");const [uploading,setUploading]=useState(false);const [caption,setCaption]=useState("");
  const eventForm=useForm({schema:eventSchema,defaultValues:{title:"",eventDate:"",venue:"",description:""}});
  const announcementForm=useForm({schema:announcementSchema,defaultValues:{title:"",body:""}});
  if(authState.type==="loading") return <div className={styles.loading}>Loading admin…</div>;
  if(authState.type!=="authenticated") return <div className={styles.loading}>Please sign in from the admin login.</div>;
  const isAdmin=authState.user.role==="admin";
  const action=async(body:any)=>{setNotice("");const r=await postAdminContent(body);setNotice(r.message);if(r.ok){await qc.invalidateQueries({queryKey:["admin-content"]});}};
  const uploadPhotos=async(files:File[])=>{const file=files[0];if(!file)return;setUploading(true);setNotice("");try{const form=new FormData();form.append("file",file);form.append("caption",caption);const r=await fetch("/_api/admin/gallery",{method:"POST",body:form,credentials:"include"});const payload=await r.json();if(!r.ok||!payload.ok)throw new Error(payload.message||"Photo upload failed.");setCaption("");setNotice("Photo added to the gallery.");await qc.invalidateQueries({queryKey:["admin-content"]});}catch(error){setNotice(error instanceof Error?error.message:"Photo upload failed.");}finally{setUploading(false);}};
  if(!isAdmin) return <PageShell eyebrow="ADMIN" title="Access restricted."><section className={styles.denied}><p>Your account is signed in, but it does not have administrator permissions.</p><Button onClick={()=>logout()}>Sign out</Button></section></PageShell>;
  const data=q.data;
  return <PageShell eyebrow="CONTROL ROOM" title="Choir admin."><section className={styles.shell}>
    <aside className={styles.side}><div><p className={styles.user}>{authState.user.displayName}</p><small>{authState.user.email}</small></div><button className={tab==="overview"?styles.active:""} onClick={()=>setTab("overview")}>Overview</button><button className={tab==="events"?styles.active:""} onClick={()=>setTab("events")}>Events</button><button className={tab==="announcements"?styles.active:""} onClick={()=>setTab("announcements")}>Announcements</button><button className={tab==="gallery"?styles.active:""} onClick={()=>setTab("gallery")}>Gallery</button><button className={tab==="inbox"?styles.active:""} onClick={()=>setTab("inbox")}>Inbox</button><button className={styles.logout} onClick={()=>logout()}>Sign out</button></aside>
    <div className={styles.main}>{notice&&<div className={styles.notice}>{notice}</div>}
      {tab==="overview"&&<><div className={styles.cards}><article><strong>{data?.events.length??0}</strong><span>Events</span></article><article><strong>{data?.announcements.length??0}</strong><span>Announcements</span></article><article><strong>{data?.auditions.length??0}</strong><span>Audition leads</span></article><article><strong>{data?.messages.length??0}</strong><span>Messages</span></article></div><div className={styles.panel}><p className={styles.label}>QUICK ACTIONS</p><h2>Keep the public site alive.</h2><p>Publish events, share announcements and review new audition interest from one place.</p></div></>}
      {tab==="events"&&<div className={styles.panel}><p className={styles.label}>EVENTS</p><h2>Publish an event</h2><Form {...eventForm}><form onSubmit={eventForm.handleSubmit(data=>action({action:"create_event",...data}))}><FormItem name="title"><FormLabel>Title</FormLabel><FormControl><Input value={eventForm.values.title} onChange={e=>eventForm.setValues(v=>({...v,title:e.target.value}))}/></FormControl><FormMessage/></FormItem><div className={styles.row}><FormItem name="eventDate"><FormLabel>Date & time</FormLabel><FormControl><Input type="datetime-local" value={eventForm.values.eventDate} onChange={e=>eventForm.setValues(v=>({...v,eventDate:e.target.value}))}/></FormControl><FormMessage/></FormItem><FormItem name="venue"><FormLabel>Venue</FormLabel><FormControl><Input value={eventForm.values.venue} onChange={e=>eventForm.setValues(v=>({...v,venue:e.target.value}))}/></FormControl><FormMessage/></FormItem></div><FormItem name="description"><FormLabel>Description</FormLabel><FormControl><Textarea value={eventForm.values.description} onChange={e=>eventForm.setValues(v=>({...v,description:e.target.value}))}/></FormControl></FormItem><Button type="submit">Publish event</Button></form></Form><div className={styles.items}>{data?.events.map((e:any)=><article key={String(e.id)}><div><strong>{e.title}</strong><span>{new Date(e.eventDate).toLocaleString()}</span><small>{e.venue}</small></div><Button onClick={()=>action({action:"delete_event",id:String(e.id)})}>Delete</Button></article>)}</div></div>}
      {tab==="announcements"&&<div className={styles.panel}><p className={styles.label}>ANNOUNCEMENTS</p><h2>Publish a notice</h2><Form {...announcementForm}><form onSubmit={announcementForm.handleSubmit(data=>action({action:"create_announcement",...data}))}><FormItem name="title"><FormLabel>Title</FormLabel><FormControl><Input value={announcementForm.values.title} onChange={e=>announcementForm.setValues(v=>({...v,title:e.target.value}))}/></FormControl><FormMessage/></FormItem><FormItem name="body"><FormLabel>Message</FormLabel><FormControl><Textarea value={announcementForm.values.body} onChange={e=>announcementForm.setValues(v=>({...v,body:e.target.value}))}/></FormControl><FormMessage/></FormItem><Button type="submit">Publish announcement</Button></form></Form><div className={styles.items}>{data?.announcements.map((a:any)=><article key={String(a.id)}><div><strong>{a.title}</strong><span>{a.body}</span></div><Button onClick={()=>action({action:"delete_announcement",id:String(a.id)})}>Delete</Button></article>)}</div></div>}
      {tab==="gallery"&&<div className={styles.panel}><p className={styles.label}>GALLERY</p><h2>Add choir photos</h2><p>Upload performance moments, rehearsals, members and community activities. JPG, PNG and WebP up to 100MB each.</p><div className={styles.uploadMeta}><Input value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Optional photo caption"/></div><FileDropzone accept="image/jpeg,image/png,image/webp" maxFiles={1} maxSize={100*1024*1024} disabled={uploading} onFilesSelected={uploadPhotos} title={uploading?"Uploading photo…":"Click to upload or drag a photo here"} subtitle="Photos are published to the public Gallery after upload."/><div className={styles.galleryGrid}>{data?.gallery.map((photo:any)=><article key={String(photo.id)}><img src={photo.imageUrl} alt={photo.caption||"The Ghetto Choir photo"}/><div className={styles.galleryMeta}><div><strong>{photo.caption||"Untitled photo"}</strong>{photo.featured&&<span>FEATURED</span>}</div><div className={styles.galleryActions}><Button onClick={async()=>{await fetch("/_api/admin/gallery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"set_featured",id:String(photo.id),featured:!photo.featured})});await qc.invalidateQueries({queryKey:["admin-content"]});}}>{photo.featured?"Unfeature":"Feature"}</Button><Button onClick={async()=>{if(confirm("Delete this photo?")){await fetch("/_api/admin/gallery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete_photo",id:String(photo.id)})});await qc.invalidateQueries({queryKey:["admin-content"]});}}}>Delete</Button></div></div></article>)}</div></div>}
      {tab==="inbox"&&<div className={styles.panel}><p className={styles.label}>INBOX</p><h2>People reaching out.</h2><h3>Audition interest</h3><div className={styles.items}>{data?.auditions.map((a:any)=><article key={String(a.id)}><div><strong>{a.fullName} · {a.age}</strong><span>{a.phone}{a.email?" · "+a.email:""}</span><small>{a.experience||"No experience note provided."}</small></div></article>)}</div><h3>Contact messages</h3><div className={styles.items}>{data?.messages.map((m:any)=><article key={String(m.id)}><div><strong>{m.name}</strong><span>{m.phone||""} {m.email?"· "+m.email:""}</span><small>{m.message}</small></div></article>)}</div></div>}
    </div>
  </section></PageShell>
}