import { useState } from "react";
import { z } from "zod";
import { PageShell } from "../components/PageShell";
import { Form,FormControl,FormItem,FormLabel,FormMessage,useForm } from "../components/Form";
import { Input } from "../components/Input";
import { Textarea } from "../components/Textarea";
import { Button } from "../components/Button";
import { postContact } from "../endpoints/public/contact_POST.schema";
import styles from "./formPage.module.css";
const contactSchema=z.object({name:z.string().min(2),email:z.string().email("Enter a valid email").optional().or(z.literal("")),phone:z.string().optional(),message:z.string().min(5)});
export default function Contact(){const [sent,setSent]=useState(false);const [error,setError]=useState("");const form=useForm({schema:contactSchema,defaultValues:{name:"",email:"",phone:"",message:""}});const submit=async(data:z.infer<typeof contactSchema>)=>{try{const r=await postContact(data);if(r.ok)setSent(true);else setError(r.message)}catch(e){setError(e instanceof Error?e.message:"Unable to send")}};return <PageShell eyebrow="GET IN TOUCH" title="Let's make some noise."><section className={styles.wrap}><div className={styles.intro}><p className={styles.label}>CONTACT THE GHETTO CHOIR UG</p><h2>Music, partnerships, performances & <span>community.</span></h2><p>For bookings, collaborations, auditions or general enquiries, reach out to the team.</p><p><strong>Phone:</strong> +256 753 314 965<br/><strong>WhatsApp:</strong> +256 701 041 017<br/><strong>Location:</strong> Kampala, Uganda</p></div><div className={styles.formCard}>{sent?<div className={styles.success}><span>✓</span><h2>Message sent.</h2><p>Thanks for reaching out. The team will follow up.</p></div>:<Form {...form}><form onSubmit={form.handleSubmit(submit)}><FormItem name="name"><FormLabel>Name</FormLabel><FormControl><Input value={form.values.name} onChange={e=>form.setValues(v=>({...v,name:e.target.value}))}/></FormControl><FormMessage/></FormItem><FormItem name="email"><FormLabel>Email</FormLabel><FormControl><Input type="email" value={form.values.email} onChange={e=>form.setValues(v=>({...v,email:e.target.value}))}/></FormControl><FormMessage/></FormItem><FormItem name="phone"><FormLabel>Phone</FormLabel><FormControl><Input value={form.values.phone} onChange={e=>form.setValues(v=>({...v,phone:e.target.value}))}/></FormControl></FormItem><FormItem name="message"><FormLabel>Message</FormLabel><FormControl><Textarea value={form.values.message} onChange={e=>form.setValues(v=>({...v,message:e.target.value}))}/></FormControl><FormMessage/></FormItem>{error&&<p className={styles.error}>{error}</p>}<Button type="submit">Send message</Button></form></Form>}</div></section></PageShell>}