import { useState } from "react";
import { z } from "zod";
import { PageShell } from "../components/PageShell";
import { Form,FormControl,FormItem,FormLabel,FormMessage,useForm } from "../components/Form";
import { Input } from "../components/Input";
import { Textarea } from "../components/Textarea";
import { Button } from "../components/Button";
import { postAudition } from "../endpoints/public/audition_POST.schema";
import styles from "./formPage.module.css";
const auditionSchema=z.object({fullName:z.string().min(2,"Enter your name"),age:z.coerce.number().int().min(12,"Recruitment starts at age 12"),phone:z.string().min(7,"Enter a valid phone number"),email:z.string().email("Enter a valid email").optional().or(z.literal("")),experience:z.string().max(1000).optional(),message:z.string().max(1500).optional()});
export default function Join(){const [sent,setSent]=useState(false);const [error,setError]=useState("");const form=useForm({schema:auditionSchema,defaultValues:{fullName:"",age:12,phone:"",email:"",experience:"",message:""}});const submit=async(data:z.infer<typeof auditionSchema>)=>{setError("");try{const r=await postAudition(data);if(r.ok)setSent(true);else setError(r.message)}catch(e){setError(e instanceof Error?e.message:"Submission failed")}};return <PageShell eyebrow="AUDITIONS" title="Your voice belongs here."><section className={styles.wrap}><div className={styles.intro}><p className={styles.label}>WE ARE RECRUITING CHORISTERS 12+</p><h2>Passion. Discipline. <span>Excellence.</span></h2><p>If you love to sing and have a heart for excellence, we want to hear you. Complete the form and the choir team can follow up with you.</p><p><strong>Call:</strong> +256 753 314 965<br/><strong>WhatsApp:</strong> +256 701 041 017<br/>Kampala, Uganda</p></div><div className={styles.formCard}>{sent?<div className={styles.success}><span>✓</span><h2>Application received.</h2><p>Thank you for your interest in The Ghetto Choir UG. We will contact you using the details you provided.</p></div>:<Form {...form}><form onSubmit={form.handleSubmit(submit)}><FormItem name="fullName"><FormLabel>Full name</FormLabel><FormControl><Input value={form.values.fullName} onChange={e=>form.setValues(v=>({...v,fullName:e.target.value}))}/></FormControl><FormMessage/></FormItem><div className={styles.row}><FormItem name="age"><FormLabel>Age</FormLabel><FormControl><Input type="number" value={form.values.age} onChange={e=>form.setValues(v=>({...v,age:Number(e.target.value)}))}/></FormControl><FormMessage/></FormItem><FormItem name="phone"><FormLabel>Phone</FormLabel><FormControl><Input value={form.values.phone} onChange={e=>form.setValues(v=>({...v,phone:e.target.value}))}/></FormControl><FormMessage/></FormItem></div><FormItem name="email"><FormLabel>Email (optional)</FormLabel><FormControl><Input type="email" value={form.values.email} onChange={e=>form.setValues(v=>({...v,email:e.target.value}))}/></FormControl><FormMessage/></FormItem><FormItem name="experience"><FormLabel>Music experience</FormLabel><FormControl><Textarea value={form.values.experience} onChange={e=>form.setValues(v=>({...v,experience:e.target.value}))} placeholder="Choir, church, school, stage, instruments…"/></FormControl><FormMessage/></FormItem><FormItem name="message"><FormLabel>Anything else?</FormLabel><FormControl><Textarea value={form.values.message} onChange={e=>form.setValues(v=>({...v,message:e.target.value}))}/></FormControl><FormMessage/></FormItem>{error&&<p className={styles.error}>{error}</p>}<Button type="submit">Submit audition interest</Button></form></Form>}</div></section></PageShell>}