import { useState } from "react";
import { z } from "zod";
import { useNavigate } from "react-router-dom";
import { Form,FormControl,FormItem,FormLabel,FormMessage,useForm } from "../components/Form";
import { Input } from "../components/Input";
import { Button } from "../components/Button";
import { postAdminSetup } from "../endpoints/admin/setup_POST.schema";
import styles from "./setup.module.css";
const schema=z.object({displayName:z.string().min(2),email:z.string().email(),password:z.string().min(8).regex(/[A-Z]/,"Use an uppercase letter").regex(/[a-z]/,"Use a lowercase letter").regex(/[0-9]/,"Use a number")});
export default function Setup(){const nav=useNavigate();const [error,setError]=useState("");const form=useForm({schema,defaultValues:{displayName:"",email:"",password:""}});const submit=async(data:z.infer<typeof schema>)=>{try{await postAdminSetup(data);nav("/admin")}catch(e){setError(e instanceof Error?e.message:"Setup failed")}};return <main className={styles.page}><div className={styles.card}><img src="https://theghettochoirug.floot.app/_cdn/static/0747ec73-d19b-4258-a261-27c26d4b8c82-ghetto-choir-logo.png" alt="The Ghetto Choir UG"/><p className={styles.label}>ONE-TIME SETUP</p><h1>Create the first admin.</h1><p>This page only works while the site has no user accounts. Choose the email and password you want to use for the choir control room.</p><Form {...form}><form onSubmit={form.handleSubmit(submit)}><FormItem name="displayName"><FormLabel>Name</FormLabel><FormControl><Input value={form.values.displayName} onChange={e=>form.setValues(v=>({...v,displayName:e.target.value}))}/></FormControl><FormMessage/></FormItem><FormItem name="email"><FormLabel>Admin email</FormLabel><FormControl><Input type="email" value={form.values.email} onChange={e=>form.setValues(v=>({...v,email:e.target.value}))}/></FormControl><FormMessage/></FormItem><FormItem name="password"><FormLabel>Password</FormLabel><FormControl><Input type="password" value={form.values.password} onChange={e=>form.setValues(v=>({...v,password:e.target.value}))}/></FormControl><FormMessage/></FormItem>{error&&<p className={styles.error}>{error}</p>}<Button type="submit">Create admin account</Button></form></Form></div></main>}